version: "3"

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      # storage
      - ./storage/db:/var/lib/mysql
    env_file:
      - ./config/db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      # storage
      - ./storage/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db # you don't need to secret this on db.env
      - REDIS_HOST=redis
    env_file:
      - ./config/db.env
    depends_on: # wait for this containers to run first
      - db
      - redis

  web:
    image: nginx
    restart: always
    volumes:
      # config
      - ./config/web/nginx.conf:/etc/nginx/nginx.conf:ro
      # storage
      - ./storage/nextcloud:/var/www/html:ro
    env_file:
      - ./config/web.env

    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      # storage
      - ./storage/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      # config
      - ./config/proxy/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
      # storage
      - ./storage/certs:/etc/nginx/certs:ro
      - ./storage/vhost/vhost.d:/etc/nginx/vhost.d
      - ./storage/html:/usr/share/nginx/html
      # docker.sock
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      # storage
      - ./storage/certs:/etc/nginx/certs
      - ./storage/vhost/vhost.d:/etc/nginx/vhost.d
      - ./storage/html:/usr/share/nginx/html
      # docker.sock
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier # isolate network to communicate only with nginx-proxy container
    depends_on:
      - proxy

  prometheus:
    image: prom/prometheus:latest
    expose: 
      - "9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    env_file: 
      - ./config/prometheus.env
    networks:
      - proxy-tier
      - default

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    expose: 
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    env_file: 
      - ./config/cadvisor.env
    networks:
      - proxy-tier
      - default

# volumes:
#   db:
#   nextcloud:
#   certs:
#   vhost.d:
#   html:

networks:
  proxy-tier:
